---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - wget
    - tar
  become: true

- name: Download Node Exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.8.0/node_exporter-1.8.0.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz
  become: true

- name: Extract Node Exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt/
    remote_src: true
  become: true

- name: Move Node Exporter binary
  command: mv /opt/node_exporter-1.8.0.linux-amd64/node_exporter /usr/local/bin/
  become: true

- name: Run Node Exporter in background (simple test mode)
  shell: nohup /usr/local/bin/node_exporter > /tmp/node_exporter.log 2>&1 &
  args:
    executable: /bin/bash
