- name: Install Python3 and pip
  apt:
    name:
      - python3
      - python3-pip
    update_cache: yes
  become: yes

- name: Install Flask
  pip:
    name: flask

- name: Copy Flask app
  copy:
    src: ../../../../flask-app/app.py
    dest: /home/ubuntu/app.py
    owner: ubuntu
    mode: '0755'

- name: Run Flask app in background
  shell: "nohup python3 /home/ubuntu/app.py &"
  args:
    executable: /bin/bash
