- name: install python3 and pip
  apt:
    name:
      - python3
      - python3-pip
    update_cache: yes
    state: present
  become: true

- name: Install Flask
  pip:
    name: flask
    executable: pip3
  become: true

- name: Copy Flask app
  copy:
    src: "{{ playbook_dir }}/../flask-app/app.py"
    dest: /home/ec2-user/app.py
    owner: ec2-user
    mode: '0755'

- name: Run Flask app in background
  shell: "pgrep -f 'python3 /home/ec2-user/app.py' || nohup python3 /home/ec2-user/app.py &"
  args:
    executable: /bin/bash
